FROM nvidia/cuda:12.4.1-base-ubuntu22.04
# Based on https://saturncloud.io/blog/how-to-install-pytorch-on-the-gpu-with-docker/
# and https://github.com/dporkka/docker-101?ysclid=m60umny7nw465329032

# Set environment variables
# ENV DEBIAN_FRONTEND=noninteractive
# RUN rm /etc/apt/sources.list.d/cuda.list && rm /etc/apt/sources.list.d/nvidia-ml.list

# Install system dependencies
# RUN apt-get update && \
#     apt-get install -y \
#         git \
#         # python3.10 \
#         python3-pip \
#         python3-dev \
#         # python3-opencv \
#         libglib2.0-0 \
#         && rm -rf /var/lib/apt/lists/*
RUN apt-get update
RUN apt-get install -y git python3-pip
# Install any python packages you need
COPY requirements.txt requirements.txt

RUN python3 -m pip install -r requirements.txt

# Upgrade pip
RUN python3 -m pip install --upgrade pip
# RUN python3 -m pip install -r requirements.txt
# RUN pip3 install mujoco==3.2.6
# RUN pip install gymnasium[classic_control]
# gymnasium[classic_control]
# roboticstoolbox-python==1.1.1 ## matplotlib>=3.8 # numpy
# imageio

# Install PyTorch and torchvision
# RUN pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html
RUN pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cu124

# Set the working directory
WORKDIR /app

RUN git clone https://github.com/alena284772/hexapod-RL

WORKDIR /app/hexapod-RL

# Set the entrypoint
# ENTRYPOINT [ "python3" ]
# CMD ["scriptname.py", "-flag"]
CMD ["bash"]